language: cpp

git:
  submodules: false
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

sudo: false

install:
  - env | grep ^TRAVIS
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      curl -L -o $CMAKE.sh http://www.cmake.org/files/v3.3/$CMAKE.sh ;
      sh $CMAKE.sh --skip-license --include-subdir ;
      export CXX="g++-4.8" ;
      export CC="gcc-4.8" ;
    fi
  - nvm install 0.12.7
  - npm install -g npm@latest
  - npm install -g node-gyp
  - curl -L https://raw.githubusercontent.com/kikitux/download-hashicorp-tools/master/download-atlas-upload.rb | ruby
  - pushd nodejs
  - npm install .
  - popd

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export CXX="g++-4.8" ;
      export CC="gcc-4.8" ;
    fi
  - $CMAKE/bin/cmake . 
  - make && time build/*t
  - node ../test/app.js
  - git clean -fdx
  - popd

env:
  - LANG="en_US.UTF-8" CMAKE="cmake-3.3.0-Linux-x86_64"

os:
  - linux

before_deploy:
  - cp build/nested build/nested-${TRAVIS_OS_NAME}
  - zip -j -r build/nested-nodejs.zip nodejs/

deploy: 
  - provider: releases
    api_key:
      secure: "ZUmRYxVIU3d9SsRrMx+c+28fAuXc+ianMp8WRKI/WbFkqZqUji5HTlLZ1dAbcH0xmukE7OVUO9vKCM1ZXAhYeTCAfVZ1y43PJatMYaVulVJmZb0+KeWKUyd3WXpSuz7dksZtaocszYkDGOlxwyOF0bIXjKfuVwf1R8GKUOuJ66Q9u10rj0TT+ZNQZHjclGSie+BDx6v/iwOXrYexgjBEnk6cBtZsVFXhiv0qCLzaxGCFMjT5R56qUToCTJgS7maNK8cK2f9pUUDa8ZE3+iE7LQiABsvgNaNSyRlRUrU/ybU82bqhr2pheFInFF7qZ9IKfzGwM7aS2dL2MJVkZN6/+qn0+Icfq2AgHJjsMR2OfbOgNUH/CHe0Zjy7/zbW31x34u3r8UE4Sizxwd+9wFGchy1i6aqqChNcYRRO5fimwzN+dbsYG6Nbl+MQHjkB73/eh/JR97zgSClcE6ej2TQoZwfOKdJR7xv518QMQBFPeg8SLfXVpe6/f3kXdpoetmmnL9mEB9UcUQgKY4lrO9f44uO6H70SZ1jjF5zupwdgo7FgUhobroSPj+iyHRYn1h+rLwxWmfXi5yfNRUiBT9yWuOYvAVuAG6UI+tFPoZTAnQceA+1hxyRum6bDeBF1UD9ZtPBTWqm4ZfvOAQsnuoCj9vUsGA7Zhv5RG1J8SaJhwy4="
    file_glob: true
    file: "build/nested-*"
    file: "build/nested-nodejs.zip"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      
after_failure:
  - uname -a
  - id
  - virt-what
  - make && time build/*t -s

after_script:
  - export tag_name="$(git describe --tags --match 'v*' | cut -d'-' -f1)"
  - echo ${tag_name}.${TRAVIS_BUILD_NUMBER}
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_TAG}" ]; then
      ./atlas-upload --token=$ATLAS_TOKEN alvaro/nested-prod nodejs/ ;
    elif [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      ./atlas-upload --token=$ATLAS_TOKEN --exclude=".packer-template" alvaro/nested-dev nodejs/ ;
    fi

notifications:
  slack:
    secure: ggFSzZkzL5ftVorFB5kH7PrWGrIgOoK2VLhjGo/x7eHVDRUNlnnINgNXOE/SbA8eV7ufrCHqVNBpuZc8qMKw+OpYSunDS5vLk+Ltw65cIHp6Ql+Pc1kQ6d8X+3epA8FBmn92enQWv8D7sVzEjW80isWUMOGmnPQtYhEm4UR93lzLTNQ/DB/1Kk1vXMN+KXeXXLy0FZrXXHNEvFRtvrnnsqG9n0/dbLmuBMYvChm1+NZb8B9wThCKJcDz4C9Wb88nejjMez8/dsnslW+BuhHczc19fnyd0apzJKf2Puowt1//UKDu9oluZpCJ6lz6Gl5kif0GxKAeAJRb06eSmklS64z8ltQk5f6LwpY9AvW01//VXNLPi/voyDWdIo61zbBB/McipEyV3Ktd9h85OFBFClmylu/evr7VuMVmaLMu15WvNnkvZL+MBewELT5xm/JdS5Zj/JprqlGeqXDv9hP/yKAVcil1bcDh2MMmSs8GUqJvkCDN7zKJrmb52WwNoCkjbnjt/YuUtdKJ4r8/EKcpe+SCMN0SgMbnIqYAk8TBDhtTY7vuyI7YUTzCJovcaPVXaDoaJAQLUt1OJRkn6mwI0hbzarel2MUxPC8QiAgHXeYaSrUOQHlaosU5MMeIu6UTSggECSzyWRpFcMhVRIcCw5A/W4M/f1EAT0Xg/2agp+o=

