language: cpp

git:
  submodules: false
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.8

sudo: false

compiler:
  - gcc

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      CMAKE="cmake-3.3.0-Linux-x86_64"
      && curl -o $CMAKE.sh http://www.cmake.org/files/v3.3/$CMAKE.sh
      && sh $CMAKE.sh --skip-license --include-subdir
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    fi
  - curl -o download-atlas-upload.rb https://raw.githubusercontent.com/kikitux/download-atlas-upload-cli/master/download-atlas-upload.rb
    && ruby download-atlas-upload.rb

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export CMAKE="cmake-3.3.0-Linux-x86_64"
      && $CMAKE/bin/cmake .
      ;
    fi
  - env | grep ^TRAVIS

script:
  - if [ "${TRAVIS_TAG}" ]; then
      make && time build/*t -s ;
    else
      make && time build/*t ;
    fi

after_script:
  - ./atlas-upload --token=$ATLAS_TOKEN alvaro/nested-dev build/nested

env:
  - LANG="en_US.UTF-8"

os:
  - linux

before_deploy:
  - cp build/nested build/nested-${TRAVIS_OS_NAME}

deploy: 
  - provider: releases
    api_key:
      secure: "ZUmRYxVIU3d9SsRrMx+c+28fAuXc+ianMp8WRKI/WbFkqZqUji5HTlLZ1dAbcH0xmukE7OVUO9vKCM1ZXAhYeTCAfVZ1y43PJatMYaVulVJmZb0+KeWKUyd3WXpSuz7dksZtaocszYkDGOlxwyOF0bIXjKfuVwf1R8GKUOuJ66Q9u10rj0TT+ZNQZHjclGSie+BDx6v/iwOXrYexgjBEnk6cBtZsVFXhiv0qCLzaxGCFMjT5R56qUToCTJgS7maNK8cK2f9pUUDa8ZE3+iE7LQiABsvgNaNSyRlRUrU/ybU82bqhr2pheFInFF7qZ9IKfzGwM7aS2dL2MJVkZN6/+qn0+Icfq2AgHJjsMR2OfbOgNUH/CHe0Zjy7/zbW31x34u3r8UE4Sizxwd+9wFGchy1i6aqqChNcYRRO5fimwzN+dbsYG6Nbl+MQHjkB73/eh/JR97zgSClcE6ej2TQoZwfOKdJR7xv518QMQBFPeg8SLfXVpe6/f3kXdpoetmmnL9mEB9UcUQgKY4lrO9f44uO6H70SZ1jjF5zupwdgo7FgUhobroSPj+iyHRYn1h+rLwxWmfXi5yfNRUiBT9yWuOYvAVuAG6UI+tFPoZTAnQceA+1hxyRum6bDeBF1UD9ZtPBTWqm4ZfvOAQsnuoCj9vUsGA7Zhv5RG1J8SaJhwy4="
    file_glob: true
    file: "build/nested-*"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  - provider: atlas
    app: alvaro/nested-prod
    include: build/nested 
    on:
      tags: true
      all_branches: true
    token:
      secure: "jjFH42u++5x+ttFHYpew+tdz4kaReYTH9ThCcSDj6kVOUbRdwx0GDqsslzrvJ8g8dPoSHvBN0iD7/fXcpxol1h2Vce8Kz2g3ub/y+KVRHmqldhUjwdG8BNBrrASttKXLxqhUpcXQrk0PouuhvfsEWNMjG7wt0owr5RpTKVrwIzZxzO3/jGH/knLve3xCRppUbxWwUhdweNrPwbQtavh926SXaGErN3hRkqOeumQfJHaua8eI6U+wFDzvSeTXNQdWmFnhyiGgdgSTXRQYh7VpVDFKogkoY+HMUwEoLgnRTXNz/jlBEGonPtSEGW9Wgf2UMCCAhPR03JGFVQ9iBUdbmTqnJ2a1dw+Yw0VZn5MRPNhko4Oh1qmLugb0utCDx2gBTdQxleqEjzcaDET0EXomEu0M4GFUem2wv/vUDXEiTnUdTQno0JQUgATzFzCODVBH3hn5o33Q2xAkBpsbuBRI++V/DH0zEK5V+Mda0Cyquay1QTZ73oMOFrbuxRdsjO80RPPAJNjFMMZp/jQWO9x9n2Q0kB1RKYycNsSxDMdaSr1+PWXAWTqPo8mSIMjvZ2i8KkSNziz0hX5QbySEZcZk+6ZWlG2WI7TNwCHPWAwdpbCcREnrcl9aG4U5P2Wv4K3YKOnvH71NlicROGvDVeRaJ8DHi3J4UJKjmKAF71qMVNk="
  - provider: atlas
    app: alvaro/nested-dev2
    include: build/nested 
    on:
      tags: false
      branch: master
    token:
      secure: "jjFH42u++5x+ttFHYpew+tdz4kaReYTH9ThCcSDj6kVOUbRdwx0GDqsslzrvJ8g8dPoSHvBN0iD7/fXcpxol1h2Vce8Kz2g3ub/y+KVRHmqldhUjwdG8BNBrrASttKXLxqhUpcXQrk0PouuhvfsEWNMjG7wt0owr5RpTKVrwIzZxzO3/jGH/knLve3xCRppUbxWwUhdweNrPwbQtavh926SXaGErN3hRkqOeumQfJHaua8eI6U+wFDzvSeTXNQdWmFnhyiGgdgSTXRQYh7VpVDFKogkoY+HMUwEoLgnRTXNz/jlBEGonPtSEGW9Wgf2UMCCAhPR03JGFVQ9iBUdbmTqnJ2a1dw+Yw0VZn5MRPNhko4Oh1qmLugb0utCDx2gBTdQxleqEjzcaDET0EXomEu0M4GFUem2wv/vUDXEiTnUdTQno0JQUgATzFzCODVBH3hn5o33Q2xAkBpsbuBRI++V/DH0zEK5V+Mda0Cyquay1QTZ73oMOFrbuxRdsjO80RPPAJNjFMMZp/jQWO9x9n2Q0kB1RKYycNsSxDMdaSr1+PWXAWTqPo8mSIMjvZ2i8KkSNziz0hX5QbySEZcZk+6ZWlG2WI7TNwCHPWAwdpbCcREnrcl9aG4U5P2Wv4K3YKOnvH71NlicROGvDVeRaJ8DHi3J4UJKjmKAF71qMVNk="
